# template

parameters:
- name: ModuleName
  type: string
- name: RepoPath
  type: string
- name: RepoName
  type: string

stages:
- template: build-module.yml
  parameters:
    ModuleName: ${{ parameters.ModuleName }}
- template: test-module.yml
  parameters:
    ModuleName: ${{ parameters.ModuleName }}
- template: deploy-module.yml
  parameters:
    ModuleName: ${{ parameters.ModuleName }}
    RepoPath: ${{ parameters.RepoPath }}
    RepoName: ${{ parameters.RepoName }}
