# template
parameters:
- name: ModuleName
  type: string
- name: RepoPath
  type: string
- name: RepoName
  type: string
- name: FailOnTestFailure
  type: boolean
  default: true
- name: GitHubPAT
  type: string
  default: "this will fail"

stages:
- template: stages/build-module.yml
  parameters:
    ModuleName: ${{ parameters.ModuleName }}
- template: stages/test-module.yml
  parameters:
    ModuleName: ${{ parameters.ModuleName }}
    FailOnTestFailure: ${{ parameters.FailOnTestFailure }}
- template: stages/deploy-module-publish-only.yml
  parameters:
    ModuleName: ${{ parameters.ModuleName }}
    RepoPath: ${{ parameters.RepoPath }}
    RepoName: ${{ parameters.RepoName }}
    GitHubPAT: ${{ parameters.GitHubPAT }}
