steps:
  - task: PipAuthenticate@1
    inputs:
      artifactFeeds: '$(System.TeamProject)/mkdocs-material-umn'
      onlyAddExtraIndex: true
  - script: |
      pip install mkdocs-material-umn mkdocs-material mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin mkdocs-markdownextradata-plugin
      mkdocs build -d $(Build.ArtifactStagingDirectory)
    displayName: mkdocs-material build
