parameters:
- name: DocsPath
  type: string
- name: CleanDestination
  type: boolean
- name: ArtifactName
  type: string
- name: Environment
  type: string
- name: BuildCondition
  type: string

jobs:
- deployment: ${{ parameters.Environment }}_windows
  condition: ${{ parameters.BuildCondition }}
  dependsOn: build
  environment:
    name: ${{ parameters.Environment }}
    resourceType: VirtualMachine
    tags: windows
  workspace:
    clean: all
  strategy:
    rolling:
      deploy:
        steps:
          #- ${{ if eq(parameters.CleanDestination, true) }}:
          - task: DeleteFiles@1
            inputs:
              SourceFolder: $(Pipeline.Workspace)
              Contents: ${{ parameters.ArtifactName }}
          - download: current
            artifact: ${{ parameters.ArtifactName }}
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/${{ parameters.ArtifactName }}'
              Contents: '**'
              TargetFolder: 'C:\inetpub\wwwroot\${{ parameters.DocsPath }}'
              CleanTargetFolder: ${{ parameters.CleanDestination }}
              OverWrite: true
- deployment: ${{ parameters.Environment }}_linux
  condition: ${{ parameters.BuildCondition }}
  dependsOn: build
  environment:
    name: ${{ parameters.Environment }}
    resourceType: VirtualMachine
    tags: linux
  workspace:
    clean: all
  strategy:
    rolling:
      deploy:
        steps:
          #- ${{ if eq(parameters.CleanDestination, true) }}:
          - task: DeleteFiles@1
            inputs:
              SourceFolder: $(Pipeline.Workspace)
              Contents: ${{ parameters.ArtifactName }}
          - download: current
            artifact: ${{ parameters.ArtifactName }}
          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(Pipeline.Workspace)/${{ parameters.ArtifactName }}'
              Contents: '**'
              TargetFolder: '/var/www/html/${{ parameters.DocsPath }}'
              CleanTargetFolder: ${{ parameters.CleanDestination }}
              OverWrite: true
