# template
parameters:
- name: DocsPath
  type: string
- name: CleanDestination
  type: boolean
  default: true
- name: ArtifactName
  type: string
  default: ''
- name: FailOnTestFailure
  type: boolean
  default: true
- name: DefaultBranch
  type: string
  default: master
- name: DevDeploys
  type: boolean
  default: false

variables:
  ${{ if contains(parameters.DocsPath, 'DocsPath') }}:
  - name: templateDocsPath
    value: ${{ variables['Build.DefinitionName'] }}
    readonly: true
  - name: templateArtifactName
    value: ${{ coalesce(parameters.ArtifactName, variables['Build.DefinitionName']) }}
    readonly: true
  ${{ else }}:
  - name: templateDocsPath
    value: ${{ parameters.DocsPath }}
    readonly: true
  - name: templateArtifactName
    value: ${{ coalesce(parameters.ArtifactName, parameters.DocsPath) }}
    readonly: true


jobs:
- job: build
  steps:
  # - ${{ if contains(parameters.DocsPath, 'DocsPath') }}:
  #   -bash: |
  #     echo '${{ variables['Build.DefinitionName'] }}'
  # - bash: |
  #     echo '${{ coalesce(parameters.DocsPath, variables['Build.DefinitionName']) }}'
  #     echo '$(Build.DefinitionName)'
  #     echo '${{ parameters.DocsPath }}'
  #     if [[ '${{ parameters.DocsPath }}' == *"DocsPath"* ]]; then exit 1; fi;
  #   displayName: Fail build if DocsPath is not set
  # - script: |
  #     sudo npm i -g markdownlint-cli
  #     markdownlint "**/*.md"
  #   continueOnError: true
  #   displayName: Run Markdownlint
  - script: |
      git clone https://github.com/FISHMANPET/markdownlint-cli.git --single-branch --branch junit "$(Agent.BuildDirectory)/markdownlint-cli"
      pushd "$(Agent.BuildDirectory)/markdownlint-cli"
      npm install
      popd
      node "$(Agent.BuildDirectory)/markdownlint-cli/markdownlint.js" -j "$(Common.TestResultsDirectory)/Test-$(Build.SourceVersion).xml" "docs/**/*.md"
    displayName: Markdown Lint
    continueOnError: true
  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: '$(Common.TestResultsDirectory)/Test-$(Build.SourceVersion).xml'
      failTaskOnFailedTests: ${{ parameters.FailOnTestFailure }}
  - script: |
      pip install mkdocs-material mkdocs-awesome-pages-plugin mkdocs-git-revision-date-localized-plugin mkdocs-markdownextradata-plugin
      mkdocs build -d $(Build.ArtifactStagingDirectory)
    displayName: mkdocs-material build
  - publish: $(Build.ArtifactStagingDirectory)
    artifact: ${{ variables.ArtifactName }}
- template: deploy-docs.yml
  parameters:
    DocsPath: ${{ variables.templateDocsPath }}
    CleanDestination: ${{ parameters.CleanDestination }}
    ArtifactName: ${{ variables.ArtifactName }}
    Environment: Dev
    BuildCondition: and(succeeded(), eq(${{ parameters.DevDeploys }}, true), startsWith(variables['build.sourceBranchName'], 'dev'))
- template: deploy-docs.yml
  parameters:
    DocsPath: ${{ variables.templateDocsPath }}
    CleanDestination: ${{ parameters.CleanDestination }}
    ArtifactName: ${{ variables.ArtifactName }}
    Environment: Tst
    BuildCondition: or(and(succeeded(), not(startsWith(variables['build.sourceBranchName'], 'dev')), eq(${{ parameters.DevDeploys }}, true)), and(succeeded(), eq(${{ parameters.DevDeploys }}, false)))
- template: deploy-docs.yml
  parameters:
    DocsPath: ${{ variables.templateDocsPath }}
    CleanDestination: ${{ parameters.CleanDestination }}
    ArtifactName: ${{ variables.ArtifactName }}
    Environment: Prd
    BuildCondition: and(succeeded(), eq(variables['build.sourceBranchName'], '${{ parameters.DefaultBranch }}'))
